# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2022-07-24 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='tasks',
            field=models.ManyToManyField(blank=True, to='portal.Tasks'),
        ),
    ]
